const types = {
    water: 'images/pkmn-type/water.png', 
    bug: 'images/pkmn-type/bug.png',
    dark: 'images/pkmn-type/dark.png',
    dragon: 'images/pkmn-type/dragon.png',
    electric: 'images/pkmn-type/electric.png',
    fairy: 'images/pkmn-type/fairy.png',
    fighting: 'images/pkmn-type/fighting.png',
    fire: 'images/pkmn-type/fire.png',
    flying: 'images/pkmn-type/flying.png',
    ghost: 'images/pkmn-type/ghost.png',
    grass: 'images/pkmn-type/grass.png',
    ground: 'images/pkmn-type/ground.png',
    ice: 'images/pkmn-type/ice.png',
    normal: 'images/pkmn-type/normal.png',
    poison: 'images/pkmn-type/poison.png',
    psychic: 'images/pkmn-type/psychic.png',
    rock: 'images/pkmn-type/rock.png',
    steel: 'images/pkmn-type/steel.png',
};

const pokemons = [
    {
        num: '001', // consertar imagem
        name: 'COATTINY',
        img: 'images/pkmn-img/001.png',
        shiny: 'images/pkmn-img-shiny/001_s.png',
        category: 'Quati Pokemon',
        ability: 'Overgrow',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass],
    },
    {
        num: '002', // consertar imagem
        name: 'COATTHIEF',
        img: 'images/pkmn-img/002.png',
        shiny: 'images/pkmn-img-shiny/002_s.png',
        category: 'Quati Pokemon',
        ability: 'Overgrow',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass, types.dark],
    },
    {
        num: '003',
        name: 'SAQUACYN',
        img: 'images/pkmn-img/003.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Hunter Pokemon',
        ability: 'Overgrow',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass, types.dark],
    },
    {
        num: '004',
        name: 'EMBRITO', 
        img: 'images/pkmn-img/004.png',
        shiny: 'images/pkmn-img-shiny/004_s.png',
        category: 'Fawn Pokemon',
        ability: 'Blaze',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fire],
    },
    {
        num: '005',
        name: 'FLAMPIPE',
        img: 'images/pkmn-img/005.png',
        shiny: 'images/pkmn-img-shiny/005_s.png',
        category: 'Fire Goat Pokemon',
        ability: 'Blaze',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fire],
    },
    {
        num: '006',
        name: 'MOTORAAM',
        img: 'images/pkmn-img/006.png',
        shiny: 'images/pkmn-img-shiny/006_s.png',
        category: 'Fire Goat Pokemon',
        ability: 'Blaze',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fire, types.steel],
    },
    {
        num: '007',
        name: 'GUAMIRIN',
        img: 'images/pkmn-img/007.png',
        shiny: 'images/pkmn-img-shiny/007_s.png',
        category: 'Tiny Crab Pokemon',
        ability: 'Torrent',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water],
    },
    {
        num: '008',
        name: 'GUAIAMURI',
        img: 'images/pkmn-img/008.png',
        shiny: 'images/pkmn-img-shiny/008_s.png',
        category: 'Guaiamum Pokemon',
        ability: 'Torrent',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water],
    },
    {
        num: '009',
        name: 'PATAIAMUM',
        img: 'images/pkmn-img/009.png',
        shiny: 'images/pkmn-img-shiny/009_s.png',
        category: 'Guaiamum Pokemon',
        ability: 'Torrent',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.ground],
    },
    {
        num: '010',
        name: 'APEGUI',
        img: 'images/pkmn-img/010.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Small Monkey Pokemon',
        ability: 'Pickup',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal],
    },
    {
        num: '011', 
        name: 'APEVOLT',
        img: 'images/pkmn-img/011.png',
        shiny: 'images/pkmn-img-shiny/011_s.png',
        category: 'Golden Pokemon',
        ability: 'Volt Absorb',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.electric],
    },
    {
        num: '012',
        name: 'VEEKRESS',
        img: 'images/pkmn-img/012.png',
        shiny: 'images/pkmn-img-shiny/012_s.png',
        category: 'Bird Pokemon',
        ability: 'Big Pecks/Moxie',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.flying, types.normal],
    },
    {
        num: '013',
        name: 'GAVKRESS',
        img: 'images/pkmn-img/013.png',
        shiny: 'images/pkmn-img-shiny/013_s.png',
        category: 'Hawk Pokemon',
        ability: 'Big Pecks/Moxie',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.flying, types.fighting],
    },
    { 
        num: '014',
        name: 'HAWKRESS',
        img: 'images/pkmn-img/014.png',
        shiny: 'images/pkmn-img-shiny/014_s.png',
        category: 'Hawk Pokemon',
        ability: 'Big Pecks/Moxie',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.flying, types.fighting],
    },
    {
        num: '015',
        name: 'SARUREK',
        img: 'images/pkmn-img/015.png',
        shiny: 'images/pkmn-img-shiny/015_s.png',
        category: 'Opossum Pokemon',
        ability: 'Reckless',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal, types.dark],
    },
    {
        num: '016',
        name: 'SAREGURO',
        img: 'images/pkmn-img/016.png',
        shiny: 'images/pkmn-img-shiny/016_s.png',
        category: 'Opossum Pokemon',
        ability: 'Reckless',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal, types.dark],
    },
    { 
        num: '017',
        name: 'PICHU',
        form: 'Regional Form',
        img: 'images/pkmn-img/017.png',
        shiny: 'images/pkmn-img-shiny/017_s.png',
        category: 'Mouse Pokemon',
        ability: 'Lighting Rod',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.electric, types.normal],
    },
    {
        num: '018',
        name: 'PIKACHU',
        form: 'Regional Form',
        img: 'images/pkmn-img/018.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Mouse Pokemon',
        ability: 'Lighting Rod',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.electric, types.normal],
    },
    {
        num: '019',
        name: 'KAICHU',
        img: 'images/pkmn-img/019.png',
        shiny: 'images/pkmn-img-shiny/019_s.png',
        category: 'Thunder Pokemon',
        ability: 'Lighting Rod',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.electric, types.fighting],
    },
    {
        num: '020',
        name: 'CAJUBI',
        img: 'images/pkmn-img/020.png',
        shiny: 'images/pkmn-img-shiny/020_s.png',
        category: 'Caju Pokemon',
        ability: 'Harvest',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass],
    },
    {
        num: '021',
        name: 'MACARAJU',
        img: 'images/pkmn-img/021.png',
        shiny: 'images/pkmn-img-shiny/021_s.png',
        category: 'Aracaju Pokemon',
        ability: 'Harvest',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass, types.flying],
    },
    {
        num: '022',
        name: 'BELLSPROUT',
        img: 'images/pkmn-img/022.png',
        shiny: 'images/pkmn-img-shiny/022_s.png',
        category: 'Flower Pokemon',
        ability: 'Chlorophyll',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass, types.poison],
    },
    {
        num: '023',
        name: 'WEEPINBELL',
        form: 'Regional Form',
        img: 'images/pkmn-img/023.png',
        shiny: 'images/pkmn-img-shiny/023_s.png',
        category: 'Toxic Flower Pokemon',
        ability: 'Chlorophyll',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.poison, types.grass],
    },
    {
        num: '024',
        name: 'TOXXIBELL',
        img: 'images/pkmn-img/024.png',
        shiny: 'images/pkmn-img-shiny/024_s.png',
        category: 'Toxic Flower Pokemon',
        ability: 'Chlorophyll',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.poison, types.grass],
    },
    {
        num: '025',
        name: 'JACIENNA',
        img: 'images/pkmn-img/025.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Water Bird Pokemon',
        ability: 'Run Away',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.flying],
    },
    {
        num: '026',
        name: 'GARCIENNA',
        img: 'images/pkmn-img/026.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Mean Bird Pokemon',
        ability: 'Intimidate',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dark, types.flying],
    },
    {
        num: '027',
        name: 'DUNDUCLE',
        img: 'images/pkmn-img/027.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Duck Pokemon',
        ability: 'Tangled Feet',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.flying],
    },
    {
        num: '028',
        name: 'PADDUCLE',
        img: 'images/pkmn-img/028.png',
        shiny: 'images/pkmn-img-shiny/028_s.png',
        category: 'Carrier Pokemon',
        ability: 'Big Pecks',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.flying],
    },
    {
        num: '029',
        name: 'STARTICK',
        img: 'images/pkmn-img/029.png',
        shiny: 'images/pkmn-img-shiny/029_s.png',
        category: 'Red Star Pokemon',
        ability: 'Poison Point',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.poison],
    },
    {
        num: '030',
        name: 'ARAMARON',
        img: 'images/pkmn-img/030.png',
        shiny: 'images/pkmn-img-shiny/030_s.png',       
        category: 'Thread Pokemon',
        ability: 'Merciless',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.poison, types.psychic],
    },
    {
        num: '031',
        name: 'JUNSPION',
        img: 'images/pkmn-img/031.png',
        shiny: 'images/pkmn-img-shiny/031_s.png',       
        category: 'Stinger Pokemon',
        ability: 'Merciless',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.poison, types.fighting],
    },
    {
        num: '032',
        name: 'COROCHI',
        img: 'images/pkmn-img/032.png',
        shiny: 'images/pkmn-img-shiny/032_s.png',       
        category: 'Roach Pokemon',
        ability: 'Run Away',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.bug, types.normal],
    },
    {
        num: '033',
        name: 'CACOROCHI',
        img: 'images/pkmn-img/033.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',       
        category: 'Super Roach Pokemon',
        ability: 'Toxic Boost',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.bug, types.ground],
    },
    {
        num: '034',
        name: 'BUDSLY',
        img: 'images/pkmn-img/034.png',
        shiny: 'images/pkmn-img-shiny/034_s.png',       
        category: 'Bud Pokemon',
        ability: 'Leaf Guard',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass],
    },
    {
        num: '035',
        name: 'TRULYWOODO',
        img: 'images/pkmn-img/035.png',
        shiny: 'images/pkmn-img-shiny/035_s.png',       
        category: 'Gardner Pokemon',
        ability: 'Green Thumb',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass],
    },
    {
        num: '036',
        name: 'TAGUARIN',
        img: 'images/pkmn-img/036.png',
        shiny: 'images/pkmn-img-shiny/036_s.png',       
        category: 'Ocelot Pokemon',
        ability: 'Run Away',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fire],
    },
    {
        num: '037',
        name: 'SIRENBY',
        img: 'images/pkmn-img/037.png',
        shiny: 'images/pkmn-img-shiny/037_s.png',       
        category: 'Manatee Pokemon',
        ability: 'Sap Sipper/Thick Fat',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water],
    },
    {
        num: '038',
        name: 'SIRENIA',
        img: 'images/pkmn-img/038.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',       
        category: 'Manatee Pokemon',
        ability: 'Sap Sipper/Thick Fat',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.ice],
    },
    {
        num: '039',
        name: 'SMIRGATOR',
        img: 'images/pkmn-img/039.png',
        shiny: 'images/pkmn-img-shiny/039_s.png',       
        category: 'Alligator Pokemon',
        ability: 'Intimidate/Anger Point',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.dark],
    },
    {
        num: '040',
        name: 'MANTYKE',
        img: 'images/pkmn-img/040.png',
        shiny: 'images/pkmn-img-shiny/040_s.png',       
        category: 'Kite Pokemon',
        ability: 'Swift Swim/Water Absorb',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.flying],
    },
    {
        num: '041',
        name: 'MANTINE',
        img: 'images/pkmn-img/041.png',
        shiny: 'images/pkmn-img-shiny/041_s.png',       
        category: 'Kite Pokemon',
        ability: 'Swift Swim/Water Absorb',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.flying],
    },
    {
        num: '042',
        name: 'MANKYTE',
        img: 'images/pkmn-img/042.png',
        shiny: 'images/pkmn-img-shiny/042_s.png',       
        category: 'Kite Pokemon',
        ability: 'Swift Swim/Water Absorb',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.flying],
    },
    {
        num: '043',
        name: 'SHRIMBODY',
        img: 'images/pkmn-img/043.png',
        shiny: 'images/pkmn-img-shiny/043_s.png',       
        category: 'Shrimp Pokemon',
        ability: 'Weak Armor',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ground, types.water],
    },
    {
        num: '044',
        name: 'SHRIMRYU',
        img: 'images/pkmn-img/044.png',
        shiny: 'images/pkmn-img-shiny/044_s.png',       
        category: 'Pitu Shrimp Pokemon',
        ability: 'Shell Armor',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dragon, types.water],
    },
    {
        num: '045',
        name: 'HORSEA',
        img: 'images/pkmn-img/045.png',
        shiny: 'images/pkmn-img-shiny/045_s.png',       
        category: 'Dragon Pokemon',
        ability: 'Swift Swim/Sniper',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dragon, types.water],
    },
    {
        num: '046',
        name: 'SEADRA',
        img: 'images/pkmn-img/046.png',
        shiny: 'images/pkmn-img-shiny/046_s.png',       
        category: 'Dragon Pokemon',
        ability: 'Swift Swim/Sniper',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dragon, types.water],
    },
    {
        num: '047',
        name: 'DRACEAN',
        img: 'images/pkmn-img/047.png',
        shiny: 'images/pkmn-img-shiny/047_s.png',       
        category: 'Dragon Pokemon',
        ability: 'Swift Swim/Intimidate',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dragon, types.dark],
    },
    {
        num: '048',
        name: 'TAMARTLE',
        img: 'images/pkmn-img/048.png',
        shiny: 'images/pkmn-img-shiny/048_s.png',       
        category: 'Turtle Pokemon',
        ability: 'Sturdy',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water],
    },
    {
        num: '049',
        name: 'COURAPAGOS',
        img: 'images/pkmn-img/049.png',
        shiny: 'images/pkmn-img-shiny/049_s.png',       
        category: 'Hard Shell Pokemon',
        ability: 'Sturdy',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.steel, types.water],
    },
    {
        num: '050',
        name: 'TENTACOOL',
        img: 'images/pkmn-img/050.png',
        shiny: 'images/pkmn-img-shiny/050_s.png',       
        category: 'Jellyfish Pokemon',
        ability: 'Poison Point/Static',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.poison, types.electric],
    },
    {
        num: '051',
        name: 'TENTAOWAR',
        img: 'images/pkmn-img/051.png',
        shiny: 'images/pkmn-img-shiny/051_s.png',       
        category: 'Jellyfish Pokemon',
        ability: 'Poison Point/Static',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.poison, types.electric],
    },
    {
        num: '052',
        name: 'ANKUSHAK',
        img: 'images/pkmn-img/052.png',
        shiny: 'images/pkmn-img-shiny/052_s.png',       
        category: 'Ancor Pokemon',
        ability: 'Strong Jaw',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.steel],
    },
    {
        num: '053',
        name: 'CUMBULLUS',
        img: 'images/pkmn-img/053.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',       
        category: 'Cloud Pokemon',
        ability: 'Cloud Nine',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fairy],
    },
    {
        num: '054',
        name: 'NUVECIAN',
        img: 'images/pkmn-img/054.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',       
        category: 'Stormy Cloud Pokemon',
        ability: 'Wind Power',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fairy, types.electric],
    },
    {
        num: '055',
        name: 'STRATERIM',
        img: 'images/pkmn-img/055.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',       
        category: 'Sunny Cloud Pokemon',
        ability: 'Wind Power',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fairy, types.fire],
    },
    {
        num: '056',
        name: 'EEVEE',
        img: 'images/pkmn-img/056.png',
        shiny: 'images/pkmn-img-shiny/056_s.png',       
        category: 'Evolution Pokemon',
        ability: 'Run Away/Adaptability',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal],
    },
    {
        num: '057',
        name: 'ACEREON',
        img: 'images/pkmn-img/057.png',
        shiny: 'images/pkmn-img-shiny/057_s.png',       
        category: 'Armor Pokemon',
        ability: 'Battle Armor',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.steel],
    },
    {
        num: '058',
        name: 'SPECTREON',
        img: 'images/pkmn-img/058.png',
        shiny: 'images/pkmn-img-shiny/058_s.png',
        category: 'Melancolic Pokemon',
        ability: 'Insomnia',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ghost],
    },
    {
        num: '059',
        name: 'DRACAREON',
        img: 'images/pkmn-img/059.png',
        shiny: 'images/pkmn-img-shiny/059_s.png',
        category: 'Scally Pokemon',
        ability: 'Shed Skin',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dragon],
    },
    {
        num: '060',
        name: 'OMYNEON',
        img: 'images/pkmn-img/060.png',
        shiny: 'images/pkmn-img-shiny/060_s.png',
        category: 'Miracle Pokemon',
        ability: 'Adaptability',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal],
    },
    {
        num: '061',
        name: 'MURIMIZU',
        img: 'images/pkmn-img/061.png',
        shiny: 'images/pkmn-img-shiny/061_s.png',
        category: 'Vessel Pokemon',
        ability: 'Water Veil',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water],
    },
    {
        num: '062',
        name: 'MIZUCLAY',
        img: 'images/pkmn-img/062.png',
        shiny: 'images/pkmn-img-shiny/062_s.png',
        category: 'Vessel Pokemon',
        ability: 'Water Absorb',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water] ,
    },
    {
        num: '063',
        name: 'AZURILL',
        img: 'images/pkmn-img/063.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Polka Dot Pokemon',
        ability: 'Thick Fat/Huge Power',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal, types.fairy],
    },
    {
        num: '064',
        name: 'MARILL',
        img: 'images/pkmn-img/064.png',
        shiny: 'images/pkmn-img-shiny/064_s.png',
        category: 'Punching Pokemon',
        ability: 'Iron Fist/Huge Power',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fighting, types.fairy],
    },
    {
        num: '065',
        name: 'PINKURILL',
        img: 'images/pkmn-img/065.png',
        shiny: 'images/pkmn-img-shiny/065_s.png',
        category: 'Punching Pokemon',
        ability: 'Iron Fist/Huge Power',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fighting, types.fairy],
    },
    {
        num: '066',
        name: 'BRIEBBLE',
        img: 'images/pkmn-img/066.png',
        shiny: 'images/pkmn-img-shiny/066_s.png',
        category: 'Pebble Pokemon',
        ability: 'Sturdy',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.rock],
    },
    {
        num: '067',
        name: 'ITABRITTA',
        img: 'images/pkmn-img/067.png',
        shiny: 'images/pkmn-img-shiny/067_s.png',
        category: 'Rock Pokemon',
        ability: 'Sturdy',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.rock],
    },
    {
        num: '068',
        name: 'PAVEGMENT',
        img: 'images/pkmn-img/068.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Street Rock Pokemon',
        ability: 'Sturdy',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.rock, types.poison],
    },
    {
        num: '069',
        name: 'DRIFLOON',
        img: 'images/pkmn-img/069.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Ballon Pokemon',
        ability: 'Flare Boost',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ghost, types.fire],
    },
    {
        num: '070',
        name: 'DRIFBLIM',
        img: 'images/pkmn-img/070.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Ballon Pokemon',
        ability: 'Flare Boost',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ghost, types.fire],
    },
    {
        num: '071',
        name: 'ERIRÉ',
        img: 'images/pkmn-img/071.png',
        shiny: 'images/pkmn-img-shiny/071_s.png',
        category: 'Entity Pokemon',
        ability: 'Anticipation',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.psychic],
    },
    {
        num: '072',
        name: 'ERIXÁ',
        img: 'images/pkmn-img/072.png',
        shiny: 'images/pkmn-img-shiny/072_s.png',
        category: 'Entity Pokemon',
        ability: 'Anticipation',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.psychic],
    },
    {
        num: '073',
        name: 'OXIRÁ',
        img: 'images/pkmn-img/073.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Entity Pokemon',
        ability: 'Justified',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.psychic, types.fighting],
    },
    {
        num: '074',
        name: 'ROSAGARTA',
        img: 'images/pkmn-img/074.png',
        shiny: 'images/pkmn-img-shiny/074_s.png',
        category: 'Larva Pokemon',
        ability: 'Shed Skin',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.bug],
    },
    {
        num: '075',
        name: 'HESALYDA',
        img: 'images/pkmn-img/075.png',
        shiny: 'images/pkmn-img-shiny/075_s.png',
        category: 'Chrysalis Pokemon',
        ability: 'Shed Skin',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.bug],
    },
    {
        num: '076',
        name: 'FLUTTYROSA',
        img: 'images/pkmn-img/076.png',
        shiny: 'images/pkmn-img-shiny/076_s.png',
        category: 'Mariposa Pokemon',
        ability: 'Dazzling',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.bug, types.psychic],
    },
    {
        num: '077',
        name: 'GYMNER',
        img: 'images/pkmn-img/077.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Flower Seed Pokemon',
        ability: 'Cute Charm',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass],
    },
    {
        num: '078',
        name: 'GYMMERINA',
        img: 'images/pkmn-img/078.png',
        shiny: 'images/pkmn-img-shiny/078_s.png',
        category: 'Flower Pokemon',
        ability: 'Flower Veil',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass, types.fairy],
    },
    {
        num: '079',
        name: 'CACTTARU',
        img: 'images/pkmn-img/079.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Fruit Pokemon',
        ability: 'Iron Barbs',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass],
    },
    {
        num: '080',
        name: 'MANKATTARU',
        img: 'images/pkmn-img/080.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Cactus Pokemon',
        ability: 'Iron Barbs',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass, types.psychic],
    },
    {
        num: '081',
        name: 'SCYTHER',
        img: 'images/pkmn-img/081.png',
        shiny: 'images/pkmn-img-shiny/081_s.png',
        category: 'Mantis Pokemon',
        ability: 'Default',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.bug, types.dragon],
    },
    {
        num: '082',
        name: 'DEFAULT',
        img: 'images/pkmn-img/082.png',
        shiny: 'images/pkmn-img-shiny/082_s.png',
        category: 'Default',
        ability: 'Default',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.bug, types.dragon],
    },
    {
        num: '083',
        name: 'CALFLING',
        img: 'images/pkmn-img/083.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Calf Pokemon',
        ability: 'Thick Fat/Scrappy',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal],
    },
    {
        num: '084',
        name: 'MILTANK',
        img: 'images/pkmn-img/084.png',
        shiny: 'images/pkmn-img-shiny/084_s.png',
        category: 'Milk Cow Pokemon',
        ability: 'Thick Fat/Cud Chew',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal, types.ground],
    },
    {
        num: '085',
        name: 'TAURUS',
        img: 'images/pkmn-img/085.png',
        shiny: 'images/pkmn-img-shiny/085_s.png',
        category: 'Farm Bull Pokemon',
        ability: 'Cud Chew/Moxie',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal, types.ground],
    },
    {
        num: '086',
        name: 'NELLAUROS',
        img: 'images/pkmn-img/086.png',
        shiny: 'images/pkmn-img-shiny/086_s.png',
        category: 'Rodeo Bull Pokemon',
        ability: 'Cud Chew/Moxie',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fighting, types.ground],
    },
    {
        num: '087',
        name: 'DEFAULT',
        img: 'images/pkmn-img/087.png',
        shiny: 'images/pkmn-img-shiny/087_s.png',
        category: 'Apparition Pokemon',
        ability: 'Night Veil',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ghost, types.water],
    },
    {
        num: '088',
        name: 'OWSCURUS',
        img: 'images/pkmn-img/088.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Apparition Pokemon',
        ability: 'Night Veil',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ghost, types.flying],
    },
    {
        num: '089',
        name: 'SKARRANKA',
        img: 'images/pkmn-img/089.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Apparition Pokemon',
        ability: 'Night Veil',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ghost, types.dark],
    },
    {
        num: '090',
        name: 'DEFAULT',
        img: 'images/pkmn-img/placeholder.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Default',
        ability: 'Default',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal],
    },
    {
        num: '091',
        name: 'LARVITAR',
        img: 'images/pkmn-img/091.png',
        shiny: 'images/pkmn-img-shiny/091_s.png',
        category: 'Rough Skin Pokemon',
        ability: 'Rough Skin',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dark, types.ground],
    },
    {
        num: '092',
        name: 'CHRISALYTAR',
        img: 'images/pkmn-img/092.png',
        shiny: 'images/pkmn-img-shiny/092_s.png',
        category: 'Chrysalis Pokemon',
        ability: 'Rough Skin',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dark, types.ground],
    },
    {
        num: '093',
        name: 'INDOMITAR',
        img: 'images/pkmn-img/093.png',
        shiny: 'images/pkmn-img-shiny/093_s.png',
        category: 'Indominable Pokemon',
        ability: 'Rough Skin',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dark, types.poison],
    },
    {
        num: '094',
        name: 'TEIURIN',
        img: 'images/pkmn-img/094.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Lizard Pokemon',
        ability: 'Intimidate',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dragon],
    },
    {
        num: '095',
        name: 'TEIRUDON',
        img: 'images/pkmn-img/095.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Lizard Pokemon',
        ability: 'Intimidate',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dragon],
    },
    {
        num: '096',
        name: 'KALARUDON',
        img: 'images/pkmn-img/096.png',
        shiny: 'images/pkmn-img-shiny/096_s.png',
        category: 'Lizard Pokemon',
        ability: 'Intimidate',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dragon],
    },
    {
        num: '097',
        name: 'BAGSLITE',
        img: 'images/pkmn-img/097.png',
        shiny: 'images/pkmn-img-shiny/097_s.png',
        category: 'Icebag Pokemon',
        ability: 'Ice Body',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ice],
    },
    {
        num: '098',
        name: 'POPSILLITE',
        img: 'images/pkmn-img/098.png',
        shiny: 'images/pkmn-img-shiny/098_s.png',
        category: 'Iceplate Pokemon',
        ability: 'Ice Body',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ice],
    },
    {
        num: '099',
        name: 'DEFAULT',
        img: 'images/pkmn-img/placeholder.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Default',
        ability: 'Default',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.normal],
    },
    {
        num: '100',
        name: 'MUNCHLAX',
        img: 'images/pkmn-img/100.png',
        shiny: 'images/pkmn-img-shiny/100_s.png',
        category: 'Snowcave Pokemon',
        ability: 'Snow Cloak/Gluttony',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ice],
    },
    {
        num: '101',
        name: 'SNORLAX',
        img: 'images/pkmn-img/101.png',
        shiny: 'images/pkmn-img-shiny/101_s.png',
        category: 'Snowcave Pokemon',
        ability: 'Snow Cloak/Gluttony',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ice, types.ghost],
    },
    { 
        num: '102',
        name: 'MAGIKING',
        img: 'images/pkmn-img/102.png',
        shiny: 'images/pkmn-img-shiny/102_s.png',
        category: 'Ancestor Pokemon',
        ability: 'Multiscale/Swift Swim',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.fighting],
    },
    {
        num: '103',
        name: 'DEFAULT',
        img: 'images/pkmn-img/103.png',
        shiny: 'images/pkmn-img-shiny/103_s.png',
        category: 'Stray Dog Pokemon',
        ability: 'Eternal Soul',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.dark],
    },
    {
        num: '104',
        name: 'DEFAULT',
        img: 'images/pkmn-img/104.png',
        shiny: 'images/pkmn-img-shiny/104_s.png',
        category: 'Stray Cat Pokemon',
        ability: 'Eternal Soul',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.psychic],
    },
    {
        num: '105',
        name: 'GRASSIBEX',
        img: 'images/pkmn-img/105.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Abundance Pokemon',
        ability: 'Evergreen',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass, types.water],
    },
    {
        num: '106',
        name: 'PHANTERRION',
        img: 'images/pkmn-img/106.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Drought Pokemon',
        ability: 'Desolation',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fire, types.ground],
    },
    {
        num: '107',
        name: 'WYSFLAMY',
        img: 'images/pkmn-img/107.png',
        shiny: 'images/pkmn-img-shiny/107_s.png',
        category: 'Wisp Pokemon',
        ability: 'Soul Fuel',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fire, types.fairy],
    },
    {
        num: '108',
        name: 'TURAIGUA',
        img: 'images/pkmn-img/108.png',
        shiny: 'images/pkmn-img-shiny/108_s.png',
        category: 'Thunder Pokemon',
        ability: 'Default',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.electric],
    },
    {
        num: '109',
        name: 'TAENTÃ',
        img: 'images/pkmn-img/placeholder.png',
        shiny: 'images/pkmn-img-shiny/placeholder.png',
        category: 'Flame Pokemon',
        ability: 'Default',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.fire],
    },
    {
        num: '110',
        name: 'YOBIUNE',
        img: 'images/pkmn-img/110.png',
        shiny: 'images/pkmn-img-shiny/110_s.png',
        category: 'River Pokemon',
        ability: 'Default',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water],
    },
    {
        num: '111',
        name: 'DEFAULT',
        img: 'images/pkmn-img/111.png',
        shiny: 'images/pkmn-img-shiny/111_s.png',
        category: 'Default',
        ability: 'Planetary Body',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.water, types.psychic],
    },
    {
        num: '112',
        name: 'DEFAULT',
        img: 'images/pkmn-img/112.png',
        shiny: 'images/pkmn-img-shiny/112_s.png',
        category: 'Default',
        ability: 'Planetary Body',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.grass, types.psychic],
    },
    {
        num: '113',
        name: 'DEFAULT',
        img: 'images/pkmn-img/113.png',
        shiny: 'images/pkmn-img-shiny/113_s.png',
        category: 'Default',
        ability: 'Planetary Body',
        height: 'Default',
        weight: 'Default',
        pokemonTypes: [types.ground, types.psychic],
    },
];

const toggleBtn = document.querySelector(".nav-toggle");
const closeBtn = document.querySelector(".nav-close")
const nav = document.querySelector(".nav");
const fixedBtn = document.querySelector(".btn-fixed");

toggleBtn.addEventListener("click", ()=>{
    if(nav.classList.contains("show-nav")){
        nav.classList.remove("show-nav");
    }
    else{
        nav.classList.add("show-nav");
    }
});

closeBtn.addEventListener("click", ()=>{
    nav.classList.remove("show-nav");
});

window.addEventListener("scroll", function(){
    if (window.scrollY >= 100){
        fixedBtn.classList.add("visible");
    } else {
        fixedBtn.classList.remove("visible");
    }
});

if (navigator.userAgent.indexOf('iPhone') > -1 ) {
    document.querySelector("[name=viewport]").setAttribute("content","width=device-width, initial-scale=1, maximum-scale=1");
}

const pkmnNum = document.querySelector(".pkmn-num");
const pkmnName = document.querySelector(".pkmn-name");
const pkmnImg = document.querySelector(".pkmn-img");
const pkmnCategory = document.querySelector(".pkmn-category");
const pkmnAbility = document.querySelector(".pkmn-ability");
const pkmnHeight = document.querySelector(".pkmn-height");
const pkmnWeight = document.querySelector(".pkmn-weight");
const pkmnType = document.querySelector(".pkmn-type--container");
const prevBtn = document.querySelector(".prev-btn");
const nextBtn = document.querySelector(".next-btn");
const searchInput = document.querySelector("#input-search");
const shinyBtn = document.querySelector(".btn-shiny");

let currentPkmn = 0;
let thisValue = true;

window.addEventListener("DOMContentLoaded", ()=>{
    const pkmnObj = pokemons[currentPkmn];
    pkmnImg.src = pkmnObj.img;
    pkmnNum.textContent = pkmnObj.num;
    pkmnName.textContent = pkmnObj.name;
    pkmnCategory.textContent = pkmnObj.category;
    pkmnAbility.textContent = pkmnObj.ability;
    pkmnHeight.textContent = pkmnObj.height;
    pkmnWeight.textContent = pkmnObj.weight;
    let imgChild = '';
    pkmnObj.pokemonTypes.forEach(function (typeUrl) {
        imgChild += `<img src=${typeUrl} class="pkmn-type">`
    })
    pkmnType.innerHTML += imgChild;
});

function showData(pkmn){
    const pkmnObj = pokemons[pkmn]
    pkmnImg.src = pkmnObj.img;
    pkmnNum.textContent = pkmnObj.num;
    pkmnName.textContent = pkmnObj.name;
    pkmnCategory.textContent = pkmnObj.category;
    pkmnAbility.textContent = pkmnObj.ability;
    pkmnHeight.textContent = pkmnObj.height;
    pkmnWeight.textContent = pkmnObj.weight;
    let imgChild = '';
    pkmnObj.pokemonTypes.forEach(function (typeUrl) {
        imgChild += `<img src=${typeUrl} class="pkmn-type">`
    })
    pkmnType.innerHTML = imgChild;
}

prevBtn.addEventListener("click", function(){
    currentPkmn--;
    if (currentPkmn < 0){
        currentPkmn = pokemons.length - 1;
    }
    showData(currentPkmn);
    thisValue = true;
});

nextBtn.addEventListener("click", function(){
    currentPkmn++;
    if (currentPkmn > pokemons.length - 1){
        currentPkmn = 0;
    }
    showData(currentPkmn);
    thisValue = true;
});

searchInput.addEventListener("keydown", function(event){
    if (event.key === "Enter") {
        if (isNaN(searchInput.value)){
            alert("Not a number");
        }
        if (searchInput.value > 113){
            alert("Not available")
        }
        let pkmnId = searchInput.value - 1;
        currentPkmn = pkmnId;
        showData(pkmnId);
        nav.classList.remove("show-nav");
        searchInput.value = "";
    } 
});

shinyBtn.addEventListener("click", function(){
    const pkmnObj = pokemons[currentPkmn];
    if (thisValue){
        pkmnImg.src = pkmnObj.shiny;
        thisValue = false;
        return
    }
    pkmnImg.src = pkmnObj.img;
    thisValue = true;
});
