const types = {
  water: "images/pkmn-type/water.png",
  bug: "images/pkmn-type/bug.png",
  dark: "images/pkmn-type/dark.png",
  dragon: "images/pkmn-type/dragon.png",
  electric: "images/pkmn-type/electric.png",
  fairy: "images/pkmn-type/fairy.png",
  fighting: "images/pkmn-type/fighting.png",
  fire: "images/pkmn-type/fire.png",
  flying: "images/pkmn-type/flying.png",
  ghost: "images/pkmn-type/ghost.png",
  grass: "images/pkmn-type/grass.png",
  ground: "images/pkmn-type/ground.png",
  ice: "images/pkmn-type/ice.png",
  normal: "images/pkmn-type/normal.png",
  poison: "images/pkmn-type/poison.png",
  psychic: "images/pkmn-type/psychic.png",
  rock: "images/pkmn-type/rock.png",
  steel: "images/pkmn-type/steel.png",
};

const pokemons = [
  {
    num: "001",
    name: "COATTINNY",
    img: "images/pkmn-img/001.png",
    shiny: "images/pkmn-img-shiny/001_s.png",
    altForm: "",
    category: "Quati Pokemon",
    ability: "Overgrow",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "001",
        name: "COATTINNY",
        img: "images/pkmn-img/001.png",
      },
      {
        num: "002",
        name: "COATTHIEF",
        img: "images/pkmn-img/002.png",
      },
      {
        num: "003",
        name: "SAQUACYN",
        img: "images/pkmn-img/003.png",
      },
    ],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass],
  },
  {
    num: "002",
    name: "COATTHIEF",
    img: "images/pkmn-img/002.png",
    shiny: "images/pkmn-img-shiny/002_s.png",
    altForm: "",
    category: "Quati Pokemon",
    ability: "Overgrow",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "001",
        name: "COATTINNY",
        img: "images/pkmn-img/001.png",
      },
      {
        num: "002",
        name: "COATTHIEF",
        img: "images/pkmn-img/002.png",
      },
      {
        num: "003",
        name: "SAQUACYN",
        img: "images/pkmn-img/003.png",
      },
    ],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.dark],
  },
  {
    num: "003",
    name: "SAQUACYN",
    img: "images/pkmn-img/003.png",
    shiny: "images/pkmn-img-shiny/003_s.png",
    altForm: "",
    category: "Hunter Pokemon",
    ability: "Overgrow",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "001",
        name: "COATTINNY",
        img: "images/pkmn-img/001.png",
      },
      {
        num: "002",
        name: "COATTHIEF",
        img: "images/pkmn-img/002.png",
      },
      {
        num: "003",
        name: "SAQUACYN",
        img: "images/pkmn-img/003.png",
      },
    ],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.dark],
  },
  {
    num: "004",
    name: "EMBRITO",
    img: "images/pkmn-img/004.png",
    shiny: "images/pkmn-img-shiny/004_s.png",
    altForm: "",
    category: "Fawn Pokemon",
    ability: "Blaze",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "004",
        name: "EMBRITO",
        img: "images/pkmn-img/004.png",
      },
      {
        num: "005",
        name: "FLAMPIPE",
        img: "images/pkmn-img/005.png",
      },
      {
        num: "006",
        name: "MOTORAAM",
        img: "images/pkmn-img/006.png",
      },
    ],
    cardColor: "#ff9d55",
    pokemonTypes: [types.fire],
  },
  {
    num: "005",
    name: "FLAMPIPE",
    img: "images/pkmn-img/005.png",
    shiny: "images/pkmn-img-shiny/005_s.png",
    altForm: "",
    category: "Fire Goat Pokemon",
    ability: "Blaze",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "004",
        name: "EMBRITO",
        img: "images/pkmn-img/004.png",
      },
      {
        num: "005",
        name: "FLAMPIPE",
        img: "images/pkmn-img/005.png",
      },
      {
        num: "006",
        name: "MOTORAAM",
        img: "images/pkmn-img/006.png",
      },
    ],
    cardColor: "#ff9d55",
    pokemonTypes: [types.fire],
  },
  {
    num: "006",
    name: "MOTORAAM",
    img: "images/pkmn-img/006.png",
    shiny: "images/pkmn-img-shiny/006_s.png",
    altForm: "",
    category: "Fire Goat Pokemon",
    ability: "Blaze",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "004",
        name: "EMBRITO",
        img: "images/pkmn-img/004.png",
      },
      {
        num: "005",
        name: "FLAMPIPE",
        img: "images/pkmn-img/005.png",
      },
      {
        num: "006",
        name: "MOTORAAM",
        img: "images/pkmn-img/006.png",
      },
    ],
    cardColor: "#ff9d55",
    pokemonTypes: [types.fire, types.steel],
  },
  {
    num: "007",
    name: "GUAMIRIN",
    img: "images/pkmn-img/007.png",
    shiny: "images/pkmn-img-shiny/007_s.png",
    altForm: "",
    category: "Tiny Crab Pokemon",
    ability: "Torrent",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "007",
        name: "GUAMIRIN",
        img: "images/pkmn-img/007.png",
      },
      {
        num: "008",
        name: "GUAIAMURI",
        img: "images/pkmn-img/008.png",
      },
      {
        num: "009",
        name: "PATAIAMUM",
        img: "images/pkmn-img/009.png",
      },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "008",
    name: "GUAIAMURI",
    img: "images/pkmn-img/008.png",
    shiny: "images/pkmn-img-shiny/008_s.png",
    altForm: "",
    category: "Guaiamum Pokemon",
    ability: "Torrent",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "007",
        name: "GUAMIRIN",
        img: "images/pkmn-img/007.png",
      },
      {
        num: "008",
        name: "GUAIAMURI",
        img: "images/pkmn-img/008.png",
      },
      {
        num: "009",
        name: "PATAIAMUM",
        img: "images/pkmn-img/009.png",
      },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "009",
    name: "PATAIAMUM",
    img: "images/pkmn-img/009.png",
    shiny: "images/pkmn-img-shiny/009_s.png",
    altForm: "",
    category: "Guaiamum Pokemon",
    ability: "Torrent",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "007",
        name: "GUAMIRIN",
        img: "images/pkmn-img/007.png",
      },
      {
        num: "008",
        name: "GUAIAMURI",
        img: "images/pkmn-img/008.png",
      },
      {
        num: "009",
        name: "PATAIAMUM",
        img: "images/pkmn-img/009.png",
      },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.ground],
  },
  {
    num: "010",
    name: "APEGUI",
    img: "images/pkmn-img/010.png",
    shiny: "images/pkmn-img-shiny/010_s.png",
    altForm: "",
    category: "Small Monkey Pokemon",
    ability: "Pickup",
    height: "0,6m",
    weight: "12kg",
    evolution: [
      {
        num: "010",
        name: "APEGUI",
        img: "images/pkmn-img/010.png",
      },
      {
        num: "011",
        name: "APEVOLT",
        img: "images/pkmn-img/011.png",
      },
    ],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal],
  },
  {
    num: "011",
    name: "APEVOLT",
    img: "images/pkmn-img/011.png",
    shiny: "images/pkmn-img-shiny/011_s.png",
    altForm: "",
    category: "Golden Pokemon",
    ability: "Volt Absorb",
    height: "1,2m",
    weight: "24kg",
    evolution: [
      {
        num: "010",
        name: "APEGUI",
        img: "images/pkmn-img/010.png",
      },
      {
        num: "011",
        name: "APEVOLT",
        img: "images/pkmn-img/011.png",
      },
    ],
    cardColor: "#f4d23c",
    pokemonTypes: [types.electric],
  },
  {
    num: "012",
    name: "VEEKRESS",
    img: "images/pkmn-img/012.png",
    shiny: "images/pkmn-img-shiny/012_s.png",
    altForm: "",
    category: "Bird Pokemon",
    ability: "Big Pecks",
    height: "0,3m",
    weight: "2kg",
    evolution: [
      {
        num: "012",
        name: "VEEKRESS",
        img: "images/pkmn-img/012.png",
      },
      {
        num: "013",
        name: "GAVKRESS",
        img: "images/pkmn-img/013.png",
      },
      {
        num: "014",
        name: "HAWKRESS",
        img: "images/pkmn-img/014.png",
      },
    ],
    cardColor: "#8fa9de",
    pokemonTypes: [types.flying, types.normal],
  },
  {
    num: "013",
    name: "GAVKRESS",
    img: "images/pkmn-img/013.png",
    shiny: "images/pkmn-img-shiny/013_s.png",
    altForm: "",
    category: "Hawk Pokemon",
    ability: "Big Pecks",
    height: "0,7m",
    weight: "20kg",
    evolution: [
      {
        num: "012",
        name: "VEEKRESS",
        img: "images/pkmn-img/012.png",
      },
      {
        num: "013",
        name: "GAVKRESS",
        img: "images/pkmn-img/013.png",
      },
      {
        num: "014",
        name: "HAWKRESS",
        img: "images/pkmn-img/014.png",
      },
    ],
    cardColor: "#8fa9de",
    pokemonTypes: [types.flying, types.fighting],
  },
  {
    num: "014",
    name: "HAWKRESS",
    img: "images/pkmn-img/014.png",
    shiny: "images/pkmn-img-shiny/014_s.png",
    altForm: "",
    category: "Hawk Pokemon",
    ability: "Big Pecks",
    height: "1,4m",
    weight: "35,8kg",
    evolution: [
      {
        num: "012",
        name: "VEEKRESS",
        img: "images/pkmn-img/012.png",
      },
      {
        num: "013",
        name: "GAVKRESS",
        img: "images/pkmn-img/013.png",
      },
      {
        num: "014",
        name: "HAWKRESS",
        img: "images/pkmn-img/014.png",
      },
    ],
    cardColor: "#8fa9de",
    pokemonTypes: [types.flying, types.fighting],
  },
  {
    num: "015",
    name: "SARUREK",
    img: "images/pkmn-img/015.png",
    shiny: "images/pkmn-img-shiny/015_s.png",
    altForm: "",
    category: "Opossum Pokemon",
    ability: "Reckless",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "015",
        name: "SARUREK",
        img: "images/pkmn-img/015.png",
      },
      {
        num: "016",
        name: "SAREGURO",
        img: "images/pkmn-img/016.png",
      },
    ],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal, types.dark],
  },
  {
    num: "016",
    name: "SAREGURO",
    img: "images/pkmn-img/016.png",
    shiny: "images/pkmn-img-shiny/016_s.png",
    altForm: "",
    category: "Opossum Pokemon",
    ability: "Reckless",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "015",
        name: "SARUREK",
        img: "images/pkmn-img/015.png",
      },
      {
        num: "016",
        name: "SAREGURO",
        img: "images/pkmn-img/016.png",
      },
    ],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal, types.dark],
  },
  {
    num: "017",
    name: "PICHU",
    img: "images/pkmn-img/017.png",
    shiny: "images/pkmn-img-shiny/017_s.png",
    altForm: "",
    category: "Mouse Pokemon",
    ability: "Lighting Rod",
    height: "0,3m",
    weight: "2kg",
    evolution: [
      {
        num: "017",
        name: "PICHU",
        img: "images/pkmn-img/017.png",
      },
      {
        num: "018",
        name: "PIKACHU",
        img: "images/pkmn-img/018.png",
      },
      {
        num: "019",
        name: "KAICHU",
        img: "images/pkmn-img/019.png",
      },
    ],
    cardColor: "#f4d23c",
    pokemonTypes: [types.electric, types.normal],
  },
  {
    num: "018",
    name: "PIKACHU",
    img: "images/pkmn-img/018.png",
    shiny: "images/pkmn-img-shiny/018_s.png",
    altForm: "",
    category: "Mouse Pokemon",
    ability: "Lighting Rod",
    height: "0,4m",
    weight: "6kg",
    evolution: [
      {
        num: "017",
        name: "PICHU",
        img: "images/pkmn-img/017.png",
      },
      {
        num: "018",
        name: "PIKACHU",
        img: "images/pkmn-img/018.png",
      },
      {
        num: "019",
        name: "KAICHU",
        img: "images/pkmn-img/019.png",
      },
    ],
    cardColor: "#f4d23c",
    pokemonTypes: [types.electric, types.normal],
  },
  {
    num: "019",
    name: "KAICHU",
    img: "images/pkmn-img/019.png",
    shiny: "images/pkmn-img-shiny/019_s.png",
    altForm: "",
    category: "Thunder Pokemon",
    ability: "Lighting Rod",
    height: "1,3m",
    weight: "55kg",
    evolution: [
      {
        num: "017",
        name: "PICHU",
        img: "images/pkmn-img/017.png",
      },
      {
        num: "018",
        name: "PIKACHU",
        img: "images/pkmn-img/018.png",
      },
      {
        num: "019",
        name: "KAICHU",
        img: "images/pkmn-img/019.png",
      },
    ],
    cardColor: "#f4d23c",
    pokemonTypes: [types.electric, types.fighting],
  },
  {
    num: "020",
    name: "CAJUBI",
    img: "images/pkmn-img/020.png",
    shiny: "images/pkmn-img-shiny/020_s.png",
    altForm: "",
    category: "Caju Pokemon",
    ability: "Harvest",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "020",
        name: "CAJUBI",
        img: "images/pkmn-img/020.png",
      },
      {
        num: "021",
        name: "MACARAJU",
        img: "images/pkmn-img/021.png",
      },
    ],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass],
  },
  {
    num: "021",
    name: "MACARAJU",
    img: "images/pkmn-img/021.png",
    shiny: "images/pkmn-img-shiny/021_s.png",
    altForm: "",
    category: "Aracaju Pokemon",
    ability: "Harvest",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "020",
        name: "CAJUBI",
        img: "images/pkmn-img/020.png",
      },
      {
        num: "021",
        name: "MACARAJU",
        img: "images/pkmn-img/021.png",
      },
    ],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.flying],
  },
  {
    num: "022",
    name: "BELLSPROUT",
    img: "images/pkmn-img/022.png",
    shiny: "images/pkmn-img-shiny/022_s.png",
    altForm: "",
    category: "Flower Pokemon",
    ability: "Chlorophyll",
    height: "0,7m",
    weight: "4kg",
    evolution: [
      {
        num: "022",
        name: "BELLSPROUT",
        img: "images/pkmn-img/022.png",
      },
      {
        num: "023",
        name: "WEEPINBELL",
        img: "images/pkmn-img/023.png",
      },
      {
        num: "024",
        name: "TOXXIBELL",
        img: "images/pkmn-img/024.png",
      },
    ],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.poison],
  },
  {
    num: "023",
    name: "WEEPINBELL",
    img: "images/pkmn-img/023.png",
    shiny: "images/pkmn-img-shiny/023_s.png",
    altForm: "",
    category: "Toxic Flower Pokemon",
    ability: "Chlorophyll",
    height: "1m",
    weight: "6,4kg",
    evolution: [
      {
        num: "022",
        name: "BELLSPROUT",
        img: "images/pkmn-img/022.png",
      },
      {
        num: "023",
        name: "WEEPINBELL",
        img: "images/pkmn-img/023.png",
      },
      {
        num: "024",
        name: "TOXXIBELL",
        img: "images/pkmn-img/024.png",
      },
    ],
    cardColor: "#aa6bc8",
    pokemonTypes: [types.poison, types.grass],
  },
  {
    num: "024",
    name: "TOXXIBELL",
    img: "images/pkmn-img/024.png",
    shiny: "images/pkmn-img-shiny/024_s.png",
    altForm: "",
    category: "Toxic Flower Pokemon",
    ability: "Chlorophyll",
    height: "1,62m",
    weight: "35,5kg",
    evolution: [
      {
        num: "022",
        name: "BELLSPROUT",
        img: "images/pkmn-img/022.png",
      },
      {
        num: "023",
        name: "WEEPINBELL",
        img: "images/pkmn-img/023.png",
      },
      {
        num: "024",
        name: "TOXXIBELL",
        img: "images/pkmn-img/024.png",
      },
    ],
    cardColor: "#aa6bc8",
    pokemonTypes: [types.poison, types.grass],
  },
  {
    num: "025",
    name: "JACIENNA",
    img: "images/pkmn-img/025.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Water Bird Pokemon",
    ability: "Run Away",
    height: "Default",
    weight: "Default",
    evolution: [
      { num: "025", name: "JACIENNA", img: "images/pkmn-img/025.png" },
      {
        num: "026",
        name: "GARCIENNA",
        img: "images/pkmn-img/026.png",
      },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.flying],
  },
  {
    num: "026",
    name: "GARCIENNA",
    img: "images/pkmn-img/026.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Mean Bird Pokemon",
    ability: "Intimidate",
    height: "Default",
    weight: "Default",
    evolution: [
      { num: "025", name: "JACIENNA", img: "images/pkmn-img/025.png" },
      {
        num: "026",
        name: "GARCIENNA",
        img: "images/pkmn-img/026.png",
      },
    ],
    cardColor: "#5b5464",
    pokemonTypes: [types.dark, types.flying],
  },
  {
    num: "027",
    name: "DUNDUCLE",
    img: "images/pkmn-img/027.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Duck Pokemon",
    ability: "Tangled Feet",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "027",
        name: "DUNDUCLE",
        img: "images/pkmn-img/027.png",
      },
      {
        num: "028",
        name: "PADDUCLE",
        img: "images/pkmn-img/028.png",
      },
    ],
    cardColor: "#8fa9de",
    pokemonTypes: [types.flying],
  },
  {
    num: "028",
    name: "PADDUCLE",
    img: "images/pkmn-img/028.png",
    shiny: "images/pkmn-img-shiny/028_s.png",
    altForm: "",
    category: "Carrier Pokemon",
    ability: "Big Pecks",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "027",
        name: "DUNDUCLE",
        img: "images/pkmn-img/027.png",
      },
      {
        num: "028",
        name: "PADDUCLE",
        img: "images/pkmn-img/028.png",
      },
    ],
    cardColor: "#8fa9de",
    pokemonTypes: [types.flying],
  },
  {
    num: "029",
    name: "STARTICK",
    img: "images/pkmn-img/029.png",
    shiny: "images/pkmn-img-shiny/029_s.png",
    altForm: "",
    category: "Red Star Pokemon",
    ability: "Poison Point",
    height: "0,1m",
    weight: "0,6kg",
    evolution: [
      { num: "029", name: "STARTICK", img: "images/pkmn-img/029.png" },
      { num: "030", name: "ARAMARON", img: "images/pkmn-img/030.png" },
    ],
    cardColor: "#aa6bc8",
    pokemonTypes: [types.poison],
  },
  {
    num: "030",
    name: "ARAMARON",
    img: "images/pkmn-img/030.png",
    shiny: "images/pkmn-img-shiny/030_s.png",
    altForm: "",
    category: "Thread Pokemon",
    ability: "Merciless",
    height: "1,3m",
    weight: "47,5kg",
    evolution: [
      { num: "029", name: "STARTICK", img: "images/pkmn-img/029.png" },
      { num: "030", name: "ARAMARON", img: "images/pkmn-img/030.png" },
    ],
    cardColor: "#aa6bc8",
    pokemonTypes: [types.poison, types.psychic],
  },
  {
    num: "031",
    name: "JUNSPION",
    img: "images/pkmn-img/031.png",
    shiny: "images/pkmn-img-shiny/031_s.png",
    altForm: "",
    category: "Stinger Pokemon",
    ability: "Merciless",
    height: "1,5m",
    weight: "42,5kg",
    evolution: [],
    cardColor: "#aa6bc8",
    pokemonTypes: [types.poison, types.fighting],
  },
  {
    num: "032",
    name: "COROCHI",
    img: "images/pkmn-img/032.png",
    shiny: "images/pkmn-img-shiny/032_s.png",
    altForm: "",
    category: "Roach Pokemon",
    ability: "Run Away",
    height: "0,2m",
    weight: "1kg",
    evolution: [
      {
        num: "032",
        name: "COROCHI",
        img: "images/pkmn-img/032.png",
      },
      {
        num: "033",
        name: "CACOROCHI",
        img: "images/pkmn-img/033.png",
      },
    ],
    cardColor: "#91c12d",
    pokemonTypes: [types.bug, types.normal],
  },
  {
    num: "033",
    name: "CACOROCHI",
    img: "images/pkmn-img/033.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Super Roach Pokemon",
    ability: "Toxic Boost",
    height: "1,5m",
    weight: "65kg",
    evolution: [
      {
        num: "032",
        name: "COROCHI",
        img: "images/pkmn-img/032.png",
      },
      {
        num: "033",
        name: "CACOROCHI",
        img: "images/pkmn-img/033.png",
      },
    ],
    cardColor: "#91c12d",
    pokemonTypes: [types.bug, types.ground],
  },
  {
    num: "034",
    name: "BUDSLY",
    img: "images/pkmn-img/034.png",
    shiny: "images/pkmn-img-shiny/034_s.png",
    altForm: "",
    category: "Bud Pokemon",
    ability: "Leaf Guard",
    height: "Default",
    weight: "Default",
    evolution: [
      { num: "034", name: "BUDSLY", img: "images/pkmn-img/034.png" },
      { num: "035", name: "TRULYWOODO", img: "images/pkmn-img/035.png" },
    ],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass],
  },
  {
    num: "035",
    name: "TRULYWOODO",
    img: "images/pkmn-img/035.png",
    shiny: "images/pkmn-img-shiny/035_s.png",
    altForm: "",
    category: "Gardner Pokemon",
    ability: "Green Thumb",
    height: "Default",
    weight: "Default",
    evolution: [
      { num: "034", name: "BUDSLY", img: "images/pkmn-img/034.png" },
      { num: "035", name: "TRULYWOODO", img: "images/pkmn-img/035.png" },
    ],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass],
  },
  {
    num: "036",
    name: "TAGUARIN",
    img: "images/pkmn-img/036.png",
    shiny: "images/pkmn-img-shiny/036_s.png",
    altForm: "",
    category: "Ocelot Pokemon",
    ability: "Run Away",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#ff9d55",
    pokemonTypes: [types.fire],
  },
  {
    num: "037",
    name: "SIRENBY",
    img: "images/pkmn-img/037.png",
    shiny: "images/pkmn-img-shiny/037_s.png",
    altForm: "",
    category: "Manatee Pokemon",
    ability: "Sap Sipper",
    height: "Default",
    weight: "Default",
    evolution: [
      { num: "037", name: "SIRENBY", img: "images/pkmn-img/037.png" },
      { num: "038", name: "SIRENIA", img: "images/pkmn-img/038.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "038",
    name: "SIRENIA",
    img: "images/pkmn-img/038.png",
    shiny: "images/pkmn-img-shiny/038_s.png",
    altForm: "",
    category: "Manatee Pokemon",
    ability: "Sap Sipper",
    height: "Default",
    weight: "Default",
    evolution: [
      { num: "037", name: "SIRENBY", img: "images/pkmn-img/037.png" },
      { num: "038", name: "SIRENIA", img: "images/pkmn-img/038.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.ice],
  },
  {
    num: "039",
    name: "SMIRGATOR",
    img: "images/pkmn-img/039.png",
    shiny: "images/pkmn-img-shiny/039_s.png",
    altForm: "",
    category: "Alligator Pokemon",
    ability: "Intimidate",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.dark],
  },
  {
    num: "040",
    name: "REMORAID",
    img: "images/pkmn-img/placeholder.png",
    shiny: "images/pkmn-img/placeholder.png",
    altForm: "",
    category: "Jet Pokemon",
    ability: "Hustle/Sniper",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "041",
    name: "OCTILLERY",
    img: "images/pkmn-img/041.png",
    shiny: "images/pkmn-img-shiny/041_s.png",
    altForm: "",
    category: "Jet Pokemon",
    ability: "Suction Cups/Sniper",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.fire],
  },
  {
    num: "042",
    name: "MANTYKE",
    img: "images/pkmn-img/042.png",
    shiny: "images/pkmn-img-shiny/042_s.png",
    altForm: "",
    category: "Kite Pokemon",
    ability: "Swift Swim",
    height: "1m",
    weight: "65kg",
    evolution: [
      { num: "042", name: "MANTYKE", img: "images/pkmn-img/042.png" },
      { num: "043", name: "MANTINE", img: "images/pkmn-img/043.png" },
      { num: "044", name: "MANKYTE", img: "images/pkmn-img/044.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "043",
    name: "MANTINE",
    img: "images/pkmn-img/043.png",
    shiny: "images/pkmn-img-shiny/043_s.png",
    altForm: "",
    category: "Kite Pokemon",
    ability: "Swift Swim",
    height: "2,1m",
    weight: "220kg",
    evolution: [
      { num: "042", name: "MANTYKE", img: "images/pkmn-img/042.png" },
      { num: "043", name: "MANTINE", img: "images/pkmn-img/043.png" },
      { num: "044", name: "MANKYTE", img: "images/pkmn-img/044.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.flying],
  },
  {
    num: "044",
    name: "MANKYTE",
    img: "images/pkmn-img/044.png",
    shiny: "images/pkmn-img-shiny/044_s.png",
    altForm: "",
    category: "Kite Pokemon",
    ability: "Swift Swim",
    height: "5m",
    weight: "850kg",
    evolution: [
      { num: "042", name: "MANTYKE", img: "images/pkmn-img/042.png" },
      { num: "043", name: "MANTINE", img: "images/pkmn-img/043.png" },
      { num: "044", name: "MANKYTE", img: "images/pkmn-img/044.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.flying],
  },
  {
    num: "045",
    name: "SHRIMBODY",
    img: "images/pkmn-img/045.png",
    shiny: "images/pkmn-img-shiny/045_s.png",
    altForm: "",
    category: "Shrimp Pokemon",
    ability: "Weak Armor",
    height: "0,3m",
    weight: "5kg",
    evolution: [
      { num: "045", name: "SHRIMBODY", img: "images/pkmn-img/045.png" },
      { num: "046", name: "SHRIMRYU", img: "images/pkmn-img/046.png" },
    ],
    cardColor: "#d97845",
    pokemonTypes: [types.ground, types.water],
  },
  {
    num: "046",
    name: "SHRIMRYU",
    img: "images/pkmn-img/046.png",
    shiny: "images/pkmn-img-shiny/046_s.png",
    altForm: "",
    category: "Pitu Shrimp Pokemon",
    ability: "Shell Armor",
    height: "1,5m",
    weight: "50,3kg",
    evolution: [
      { num: "045", name: "SHRIMBODY", img: "images/pkmn-img/045.png" },
      { num: "046", name: "SHRIMRYU", img: "images/pkmn-img/046.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.dragon, types.water],
  },
  {
    num: "047",
    name: "HORSEA",
    img: "images/pkmn-img/047.png",
    shiny: "images/pkmn-img-shiny/047_s.png",
    altForm: "",
    category: "Dragon Pokemon",
    ability: "Swift Swim",
    height: "0,4m",
    weight: "8kg",
    evolution: [
      { num: "047", name: "HORSEA", img: "images/pkmn-img/047.png" },
      { num: "048", name: "SEADRA", img: "images/pkmn-img/048.png" },
      { num: "049", name: "DRACEAN", img: "images/pkmn-img/049.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.dragon, types.water],
  },
  {
    num: "048",
    name: "SEADRA",
    img: "images/pkmn-img/048.png",
    shiny: "images/pkmn-img-shiny/048_s.png",
    altForm: "",
    category: "Dragon Pokemon",
    ability: "Swift Swim",
    height: "1,2m",
    weight: "25kg",
    evolution: [
      { num: "047", name: "HORSEA", img: "images/pkmn-img/047.png" },
      { num: "048", name: "SEADRA", img: "images/pkmn-img/048.png" },
      { num: "049", name: "DRACEAN", img: "images/pkmn-img/049.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.dragon, types.poison],
  },
  {
    num: "049",
    name: "DRACEAN",
    img: "images/pkmn-img/049.png",
    shiny: "images/pkmn-img-shiny/049_s.png",
    altForm: "",
    category: "Dragon Pokemon",
    ability: "Swift Swim",
    height: "2,3m",
    weight: "180kg",
    evolution: [
      { num: "047", name: "HORSEA", img: "images/pkmn-img/047.png" },
      { num: "048", name: "SEADRA", img: "images/pkmn-img/048.png" },
      { num: "049", name: "DRACEAN", img: "images/pkmn-img/049.png" },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.dragon, types.poison],
  },
  {
    num: "050",
    name: "TAMARTLE",
    img: "images/pkmn-img/050.png",
    shiny: "images/pkmn-img-shiny/050_s.png",
    altForm: "",
    category: "Turtle Pokemon",
    ability: "Sturdy",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "050",
        name: "TAMARTLE",
        img: "images/pkmn-img/050.png",
      },
      {
        num: "051",
        name: "COURAPAGOS",
        img: "images/pkmn-img/051.png",
      },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "051",
    name: "COURAPAGOS",
    img: "images/pkmn-img/051.png",
    shiny: "images/pkmn-img-shiny/051_s.png",
    altForm: "",
    category: "Hard Shell Pokemon",
    ability: "Sturdy",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "050",
        name: "TAMARTLE",
        img: "images/pkmn-img/050.png",
      },
      {
        num: "051",
        name: "COURAPAGOS",
        img: "images/pkmn-img/051.png",
      },
    ],
    cardColor: "#5a8ea2",
    pokemonTypes: [types.steel, types.water],
  },
  {
    num: "052",
    name: "TENTACOOL",
    img: "images/pkmn-img/052.png",
    shiny: "images/pkmn-img-shiny/052_s.png",
    altForm: "",
    category: "Jellyfish Pokemon",
    ability: "Poison Point",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "052",
        name: "TENTACOOL",
        img: "images/pkmn-img/052.png",
      },
      {
        num: "053",
        name: "TENTAWARU",
        img: "images/pkmn-img/053.png",
      },
    ],
    cardColor: "#aa6bc8",
    pokemonTypes: [types.poison, types.electric],
  },
  {
    num: "053",
    name: "TENTAWARU",
    img: "images/pkmn-img/053.png",
    shiny: "images/pkmn-img-shiny/053_s.png",
    altForm: "",
    category: "Jellyfish Pokemon",
    ability: "Poison Point",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "052",
        name: "TENTACOOL",
        img: "images/pkmn-img/052.png",
      },
      {
        num: "053",
        name: "TENTAWARU",
        img: "images/pkmn-img/053.png",
      },
    ],
    cardColor: "#aa6bc8",
    pokemonTypes: [types.poison, types.electric],
  },
  {
    num: "054",
    name: "ANKUSHAK",
    img: "images/pkmn-img/054.png",
    shiny: "images/pkmn-img-shiny/054_s.png",
    altForm: "",
    category: "Anchor Pokemon",
    ability: "Strong Jaw",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.steel],
  },
  {
    num: "055",
    name: "CUMBULLUS",
    img: "images/pkmn-img/055.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Cloud Pokemon",
    ability: "Cloud Nine",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#ec8fe6",
    pokemonTypes: [types.fairy],
  },
  {
    num: "056",
    name: "NUVECIAN",
    img: "images/pkmn-img/056.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Stormy Cloud Pokemon",
    ability: "Wind Power",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "055",
        name: "CUMBULLUS",
        img: "images/pkmn-img/055.png",
      },
      {
        num: "056",
        name: "NUVECIAN",
        img: "images/pkmn-img/056.png",
      },
    ],
    cardColor: "#ec8fe6",
    pokemonTypes: [types.fairy, types.electric],
  },
  {
    num: "057",
    name: "STRATERIM",
    img: "images/pkmn-img/057.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Sunny Cloud Pokemon",
    ability: "Wind Power",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "055",
        name: "CUMBULLUS",
        img: "images/pkmn-img/055.png",
      },
      {
        num: "057",
        name: "STRATERIM",
        img: "images/pkmn-img/057.png",
      },
    ],
    cardColor: "#ec8fe6",
    pokemonTypes: [types.fairy, types.fire],
  },
  {
    num: "058",
    name: "EEVEE",
    img: "images/pkmn-img/058.png",
    shiny: "images/pkmn-img-shiny/058_s.png",
    altForm: "",
    category: "Evolution Pokemon",
    ability: "Run Away",
    height: "0,4m",
    weight: "6,5kg",
    evolution: [],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal],
  },
  {
    num: "059",
    name: "ACEREON",
    img: "images/pkmn-img/059.png",
    shiny: "images/pkmn-img-shiny/059_s.png",
    altForm: "",
    category: "Armor Pokemon",
    ability: "Battle Armor",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "058",
        name: "EEVEE",
        img: "images/pkmn-img/058.png",
      },
      {
        num: "059",
        name: "ACEREON",
        img: "images/pkmn-img/059.png",
      },
    ],
    cardColor: "#5a8ea2",
    pokemonTypes: [types.steel],
  },
  {
    num: "060",
    name: "SPECTREON",
    img: "images/pkmn-img/060.png",
    shiny: "images/pkmn-img-shiny/060_s.png",
    altForm: "",
    category: "Melancholic Pokemon",
    ability: "Insomnia",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "058",
        name: "EEVEE",
        img: "images/pkmn-img/058.png",
      },
      {
        num: "060",
        name: "SPECTREON",
        img: "images/pkmn-img/060.png",
      },
    ],
    cardColor: "#5269ad",
    pokemonTypes: [types.ghost],
  },
  {
    num: "061",
    name: "DRACAREON",
    img: "images/pkmn-img/061.png",
    shiny: "images/pkmn-img-shiny/061_s.png",
    altForm: "",
    category: "Scaly Pokemon",
    ability: "Shed Skin",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "058",
        name: "EEVEE",
        img: "images/pkmn-img/058.png",
      },
      {
        num: "061",
        name: "DRACAREON",
        img: "images/pkmn-img/061.png",
      },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.dragon],
  },
  {
    num: "062",
    name: "OMYNEON",
    img: "images/pkmn-img/062.png",
    shiny: "images/pkmn-img-shiny/062_s.png",
    altForm: "",
    category: "Miracle Pokemon",
    ability: "Adaptability",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "058",
        name: "EEVEE",
        img: "images/pkmn-img/058.png",
      },
      {
        num: "062",
        name: "OMYNEON",
        img: "images/pkmn-img/062.png",
      },
    ],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal],
  },
  {
    num: "063",
    name: "MURIMIZU",
    img: "images/pkmn-img/063.png",
    shiny: "images/pkmn-img-shiny/063_s.png",
    altForm: "",
    category: "Vessel Pokemon",
    ability: "Water Veil",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "063",
        name: "MURIMIZU",
        img: "images/pkmn-img/063.png",
      },
      {
        num: "064",
        name: "MIZUCLAY",
        img: "images/pkmn-img/064.png",
      },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "064",
    name: "MIZUCLAY",
    img: "images/pkmn-img/064.png",
    shiny: "images/pkmn-img-shiny/064_s.png",
    altForm: "",
    category: "Vessel Pokemon",
    ability: "Water Absorb",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "063",
        name: "MURIMIZU",
        img: "images/pkmn-img/063.png",
      },
      {
        num: "064",
        name: "MIZUCLAY",
        img: "images/pkmn-img/064.png",
      },
    ],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "065",
    name: "AZURILL",
    img: "images/pkmn-img/065.png",
    shiny: "images/pkmn-img-shiny/065_s.png",
    altForm: "",
    category: "Polka Dot Pokemon",
    ability: "Thick Fat",
    height: "0,2m",
    weight: "2kg",
    evolution: [
      {
        num: "065",
        name: "AZURILL",
        img: "images/pkmn-img/065.png",
      },
      {
        num: "066",
        name: "MARILL",
        img: "images/pkmn-img/066.png",
      },
      {
        num: "067",
        name: "PINKURILL",
        img: "images/pkmn-img/067.png",
      },
    ],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal, types.fairy],
  },
  {
    num: "066",
    name: "MARILL",
    img: "images/pkmn-img/066.png",
    shiny: "images/pkmn-img-shiny/066_s.png",
    altForm: "",
    category: "Punching Pokemon",
    ability: "Iron Fist",
    height: "0,6m",
    weight: "10kg",
    evolution: [
      {
        num: "065",
        name: "AZURILL",
        img: "images/pkmn-img/065.png",
      },
      {
        num: "066",
        name: "MARILL",
        img: "images/pkmn-img/066.png",
      },
      {
        num: "067",
        name: "PINKURILL",
        img: "images/pkmn-img/067.png",
      },
    ],
    cardColor: "#ce416b",
    pokemonTypes: [types.fighting, types.fairy],
  },
  {
    num: "067",
    name: "PINKURILL",
    img: "images/pkmn-img/067.png",
    shiny: "images/pkmn-img-shiny/067_s.png",
    altForm: "",
    category: "Punching Pokemon",
    ability: "Iron Fist",
    height: "1m",
    weight: "35kg",
    evolution: [
      {
        num: "065",
        name: "AZURILL",
        img: "images/pkmn-img/065.png",
      },
      {
        num: "066",
        name: "MARILL",
        img: "images/pkmn-img/066.png",
      },
      {
        num: "067",
        name: "PINKURILL",
        img: "images/pkmn-img/067.png",
      },
    ],
    cardColor: "#ce416b",
    pokemonTypes: [types.fighting, types.fairy],
  },
  {
    num: "068",
    name: "BRIEBBLE",
    img: "images/pkmn-img/068.png",
    shiny: "images/pkmn-img-shiny/068_s.png",
    altForm: "",
    category: "Pebble Pokemon",
    ability: "Sturdy",
    height: "0,3m",
    weight: "3kg",
    evolution: [
      {
        num: "068",
        name: "BRIEBBLE",
        img: "images/pkmn-img/068.png",
      },
      {
        num: "069",
        name: "ITABRITTA",
        img: "images/pkmn-img/069.png",
      },
      {
        num: "070",
        name: "PAVEGMENT",
        img: "images/pkmn-img/070.png",
      },
    ],
    cardColor: "#c5b78c",
    pokemonTypes: [types.rock],
  },
  {
    num: "069",
    name: "ITABRITTA",
    img: "images/pkmn-img/069.png",
    shiny: "images/pkmn-img-shiny/069_s.png",
    altForm: "",
    category: "Rock Pokemon",
    ability: "Sturdy",
    height: "0,6m",
    weight: "7kg",
    evolution: [
      {
        num: "068",
        name: "BRIEBBLE",
        img: "images/pkmn-img/068.png",
      },
      {
        num: "069",
        name: "ITABRITTA",
        img: "images/pkmn-img/069.png",
      },
      {
        num: "070",
        name: "PAVEGMENT",
        img: "images/pkmn-img/070.png",
      },
    ],
    cardColor: "#c5b78c",
    pokemonTypes: [types.rock],
  },
  {
    num: "070",
    name: "PAVEGMENT",
    img: "images/pkmn-img/070.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Street Rock Pokemon",
    ability: "Sturdy",
    height: "1,3m",
    weight: "65kg",
    evolution: [
      {
        num: "068",
        name: "BRIEBBLE",
        img: "images/pkmn-img/068.png",
      },
      {
        num: "069",
        name: "ITABRITTA",
        img: "images/pkmn-img/069.png",
      },
      {
        num: "070",
        name: "PAVEGMENT",
        img: "images/pkmn-img/070.png",
      },
    ],
    cardColor: "#c5b78c",
    pokemonTypes: [types.rock, types.poison],
  },
  {
    num: "071",
    name: "DRIFLOON",
    img: "images/pkmn-img/071.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Ballon Pokemon",
    ability: "Flare Boost",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "071",
        name: "DRIFLOON",
        img: "images/pkmn-img/071.png",
      },
      {
        num: "072",
        name: "DRIFBLIM",
        img: "images/pkmn-img/072.png",
      },
    ],
    cardColor: "#5269ad",
    pokemonTypes: [types.ghost, types.fire],
  },
  {
    num: "072",
    name: "DRIFBLIM",
    img: "images/pkmn-img/072.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Ballon Pokemon",
    ability: "Flare Boost",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "071",
        name: "DRIFLOON",
        img: "images/pkmn-img/071.png",
      },
      {
        num: "072",
        name: "DRIFBLIM",
        img: "images/pkmn-img/072.png",
      },
    ],
    cardColor: "#5269ad",
    pokemonTypes: [types.ghost, types.fire],
  },
  {
    num: "073",
    name: "ERIRÉ",
    img: "images/pkmn-img/073.png",
    shiny: "images/pkmn-img-shiny/073_s.png",
    altForm: "",
    category: "Entity Pokemon",
    ability: "Anticipation",
    height: "0,3m",
    weight: "2kg",
    evolution: [],
    cardColor: "#fa7179",
    pokemonTypes: [types.psychic],
  },
  {
    num: "074",
    name: "ERIXÁ",
    img: "images/pkmn-img/074.png",
    shiny: "images/pkmn-img-shiny/074_s.png",
    altForm: "",
    category: "Entity Pokemon",
    ability: "Anticipation",
    height: "0,7m",
    weight: "10kg",
    evolution: [],
    cardColor: "#fa7179",
    pokemonTypes: [types.psychic],
  },
  {
    num: "075",
    name: "OXIRÁ",
    img: "images/pkmn-img/075.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Entity Pokemon",
    ability: "Justified",
    height: "1,5m",
    weight: "65kg",
    evolution: [],
    cardColor: "#fa7179",
    pokemonTypes: [types.psychic, types.fighting],
  },
  {
    num: "076",
    name: "ROSAGARTA",
    img: "images/pkmn-img/076.png",
    shiny: "images/pkmn-img-shiny/076_s.png",
    altForm: "",
    category: "Larva Pokemon",
    ability: "Shed Skin",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#91c12d",
    pokemonTypes: [types.bug],
  },
  {
    num: "077",
    name: "HESALYDA",
    img: "images/pkmn-img/077.png",
    shiny: "images/pkmn-img-shiny/077_s.png",
    altForm: "",
    category: "Chrysalis Pokemon",
    ability: "Shed Skin",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#91c12d",
    pokemonTypes: [types.bug],
  },
  {
    num: "078",
    name: "FLUTTYROSA",
    img: "images/pkmn-img/078.png",
    shiny: "images/pkmn-img-shiny/078_s.png",
    altForm: "",
    category: "Mariposa Pokemon",
    ability: "Dazzling",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#91c12d",
    pokemonTypes: [types.bug, types.psychic],
  },
  {
    num: "079",
    name: "PRETTYFLORA",
    img: "images/pkmn-img/079.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Flower Seed Pokemon",
    ability: "Cute Charm",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass],
  },
  {
    num: "080",
    name: "FLEURLLET",
    img: "images/pkmn-img/080.png",
    shiny: "images/pkmn-img-shiny/080_s.png",
    altForm: "",
    category: "Flower Pokemon",
    ability: "Flower Veil",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.fairy],
  },
  {
    num: "081",
    name: "CACTTARU",
    img: "images/pkmn-img/081.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Fruit Pokemon",
    ability: "Iron Barbs",
    height: "0,3m",
    weight: "1,5kg",
    evolution: [],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass],
  },
  {
    num: "082",
    name: "MANKATTARU",
    img: "images/pkmn-img/082.png",
    shiny: "images/pkmn-img-shiny/082_s.png",
    altForm: "",
    category: "Cactus Pokemon",
    ability: "Iron Barbs",
    height: "0,6m",
    weight: "15kg",
    evolution: [],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.psychic],
  },
  {
    num: "083",
    name: "BRAMBLIN",
    img: "images/pkmn-img/placeholder.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Tumbleweed Pokemon",
    ability: "Wind Rider",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.ghost],
  },
  {
    num: "084",
    name: "BRAMBLEGHAST",
    img: "images/pkmn-img/placeholder.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Tumbleweed Pokemon",
    ability: "Wind Rider",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.ghost],
  },
  {
    num: "085",
    name: "SCYTHER",
    img: "images/pkmn-img/085.png",
    shiny: "images/pkmn-img-shiny/085_s.png",
    altForm: "",
    category: "Mantis Pokemon",
    ability: "Battle Armor",
    height: "1,5m",
    weight: "56kg",
    evolution: [],
    cardColor: "#91c12d",
    pokemonTypes: [types.bug, types.dragon],
  },
  {
    num: "086",
    name: "DRAKANTIS",
    img: "images/pkmn-img/086.png",
    shiny: "images/pkmn-img-shiny/086_s.png",
    altForm: "",
    category: "Draconic Pokemon",
    ability: "Battle Armor",
    height: "1,75m",
    weight: "87,5kg",
    evolution: [],
    cardColor: "#91c12d",
    pokemonTypes: [types.bug, types.dragon],
  },
  {
    num: "087",
    name: "MIRINDUÁ",
    img: "images/pkmn-img/087.png",
    shiny: "images/pkmn-img-shiny/087_s.png",
    altForm: "",
    category: "Anteater Pokemon",
    ability: "Gluttony",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "087",
        name: "MIRINDUÁ",
        img: "images/pkmn-img/087.png",
      },
      {
        num: "088",
        name: "TAMADUNYA",
        img: "images/pkmn-img/088.png",
      },
    ],
    cardColor: "#ce416b",
    pokemonTypes: [types.fighting],
  },
  {
    num: "088",
    name: "TAMADUNYA",
    img: "images/pkmn-img/088.png",
    shiny: "images/pkmn-img-shiny/088_s.png",
    altForm: "",
    category: "Anteater Pokemon",
    ability: "Gluttony",
    height: "Default",
    weight: "Default",
    evolution: [
      {
        num: "087",
        name: "MIRINDUÁ",
        img: "images/pkmn-img/087.png",
      },
      {
        num: "088",
        name: "TAMADUNYA",
        img: "images/pkmn-img/088.png",
      },
    ],
    cardColor: "#ce416b",
    pokemonTypes: [types.fighting, types.ground],
  },
  {
    num: "089",
    name: "CALFLING",
    img: "images/pkmn-img/089.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Calf Pokemon",
    ability: "Thick Fat",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal],
  },
  {
    num: "090",
    name: "MILTANK",
    img: "images/pkmn-img/090.png",
    shiny: "images/pkmn-img-shiny/090_s.png",
    altForm: "",
    category: "Milk Cow Pokemon",
    ability: "Thick Fat",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal, types.ground],
  },
  {
    num: "091",
    name: "TAURUS",
    img: "images/pkmn-img/091.png",
    shiny: "images/pkmn-img-shiny/091_s.png",
    altForm: "",
    category: "Farm Bull Pokemon",
    ability: "Cud Chew/Moxie",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal, types.ground],
  },
  {
    num: "092",
    name: "NELLAUROS",
    img: "images/pkmn-img/092.png",
    shiny: "images/pkmn-img-shiny/092_s.png",
    altForm: "",
    category: "Rodeo Bull Pokemon",
    ability: "Cud Chew/Moxie",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#ce416b",
    pokemonTypes: [types.fighting, types.ground],
  },
  {
    num: "093",
    name: "LECHONK",
    img: "images/pkmn-img/placeholder.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Hog Pokemon",
    ability: "Aroma Veil/Gluttony",
    height: "0,5m",
    weight: "10,2kg",
    evolution: [],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal],
  },
  {
    num: "094",
    name: "Default",
    img: "images/pkmn-img/094.png",
    shiny: "images/pkmn-img-shiny/094_s.png",
    altForm: "",
    category: "Hog Pokemon",
    ability: "Solid Rock",
    height: "1m",
    weight: "300kg",
    evolution: [],
    cardColor: "#c5b78c",
    pokemonTypes: [types.rock],
  },
  {
    num: "095",
    name: "DEFAULT",
    img: "images/pkmn-img/095.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Apparition Pokemon",
    ability: "Night Veil",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5269ad",
    pokemonTypes: [types.ghost, types.water],
  },
  {
    num: "096",
    name: "OWSCURUS",
    img: "images/pkmn-img/096.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Apparition Pokemon",
    ability: "Night Veil",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5269ad",
    pokemonTypes: [types.ghost, types.flying],
  },
  {
    num: "097",
    name: "SKARRANKA",
    img: "images/pkmn-img/097.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Apparition Pokemon",
    ability: "Night Veil",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5269ad",
    pokemonTypes: [types.ghost, types.dark],
  },
  {
    num: "098",
    name: "DEFAULT",
    img: "images/pkmn-img/placeholder.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Default",
    ability: "Default",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#919aa2",
    pokemonTypes: [types.normal],
  },
  {
    num: "099",
    name: "LARVITAR",
    img: "images/pkmn-img/099.png",
    shiny: "images/pkmn-img-shiny/099_s.png",
    altForm: "",
    category: "Rough Skin Pokemon",
    ability: "Rough Skin",
    height: "0,7m",
    weight: "72kg",
    evolution: [],
    cardColor: "#5b5464",
    pokemonTypes: [types.dark, types.ground],
  },
  {
    num: "100",
    name: "CHRISALYTAR",
    img: "images/pkmn-img/100.png",
    shiny: "images/pkmn-img-shiny/100_s.png",
    altForm: "",
    category: "Chrysalis Pokemon",
    ability: "Rough Skin",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5b5464",
    pokemonTypes: [types.dark, types.ground],
  },
  {
    num: "101",
    name: "INDOMITAR",
    img: "images/pkmn-img/101.png",
    shiny: "images/pkmn-img-shiny/101_s.png",
    altForm: "",
    category: "Indominable Pokemon",
    ability: "Rough Skin",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5b5464",
    pokemonTypes: [types.dark, types.poison],
  },
  {
    num: "102",
    name: "TEIURIN",
    img: "images/pkmn-img/102.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Lizard Pokemon",
    ability: "Intimidate",
    height: "0,6m",
    weight: "8kg",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.dragon],
  },
  {
    num: "103",
    name: "TEIRUDON",
    img: "images/pkmn-img/103.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Lizard Pokemon",
    ability: "Intimidate",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.dragon],
  },
  {
    num: "104",
    name: "KALARUDON",
    img: "images/pkmn-img/104.png",
    shiny: "images/pkmn-img-shiny/104_s.png",
    altForm: "",
    category: "Lizard Pokemon",
    ability: "Intimidate",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.dragon],
  },
  {
    num: "105",
    name: "BAGSLITE",
    img: "images/pkmn-img/105.png",
    shiny: "images/pkmn-img-shiny/105_s.png",
    altForm: "",
    category: "Icebag Pokemon",
    ability: "Ice Body",
    height: "0,35m",
    weight: "2,5kg",
    evolution: [
      { num: "105", name: "BAGSLITE", img: "images/pkmn-img/105.png" },
      { num: "106", name: "POPSILLITE", img: "images/pkmn-img/106.png" },
      { num: "107", name: "POPSPLATE", img: "images/pkmn-img/107.png" },
    ],
    cardColor: "#73cec0",
    pokemonTypes: [types.ice],
  },
  {
    num: "106",
    name: "POPSILLITE",
    img: "images/pkmn-img/106.png",
    shiny: "images/pkmn-img-shiny/106_s.png",
    altForm: "",
    category: "Iceplate Pokemon",
    ability: "Ice Body",
    height: "0,6m",
    weight: "12kg",
    evolution: [
      { num: "105", name: "BAGSLITE", img: "images/pkmn-img/105.png" },
      { num: "106", name: "POPSILLITE", img: "images/pkmn-img/106.png" },
      { num: "107", name: "POPSPLATE", img: "images/pkmn-img/107.png" },
    ],
    cardColor: "#73cec0",
    pokemonTypes: [types.ice],
  },
  {
    num: "107",
    name: "POPSPLATE",
    img: "images/pkmn-img/107.png",
    shiny: "images/pkmn-img-shiny/107_s.png",
    altForm: "",
    category: "Iceplate Pokemon",
    ability: "Ice Body",
    height: "1,5m",
    weight: "62kg",
    evolution: [
      { num: "105", name: "BAGSLITE", img: "images/pkmn-img/105.png" },
      { num: "106", name: "POPSILLITE", img: "images/pkmn-img/106.png" },
      { num: "107", name: "POPSPLATE", img: "images/pkmn-img/107.png" },
    ],
    cardColor: "#73cec0",
    pokemonTypes: [types.ice],
  },
  {
    num: "108",
    name: "MUNCHLAX",
    img: "images/pkmn-img/108.png",
    shiny: "images/pkmn-img-shiny/108_s.png",
    altForm: "",
    category: "Snowcave Pokemon",
    ability: "Snow Cloak",
    height: "Default",
    weight: "Default",
    evolution: [
      { num: "108", name: "MUNCHLAX", img: "images/pkmn-img/108.png" },
      { num: "109", name: "SNORLAX", img: "images/pkmn-img/109.png" },
    ],
    cardColor: "#73cec0",
    pokemonTypes: [types.ice],
  },
  {
    num: "109",
    name: "SNORLAX",
    img: "images/pkmn-img/109.png",
    shiny: "images/pkmn-img-shiny/109_s.png",
    altForm: "",
    category: "Snowcave Pokemon",
    ability: "Snow Cloak",
    height: "Default",
    weight: "Default",
    evolution: [
      { num: "108", name: "MUNCHLAX", img: "images/pkmn-img/108.png" },
      { num: "109", name: "SNORLAX", img: "images/pkmn-img/109.png" },
    ],
    cardColor: "#73cec0",
    pokemonTypes: [types.ice, types.ghost],
  },
  {
    num: "110",
    name: "MAGIKING",
    img: "images/pkmn-img/110.png",
    shiny: "images/pkmn-img-shiny/110_s.png",
    altForm: "images/pkmn-img/110_f.png",
    altFormShiny: "images/pkmn-img-shiny-shiny/110_fs.png",
    category: "Ancestor Pokemon",
    ability: "Multiscale",
    height: "1,53",
    weight: "20,4kg",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.fighting],
  },
  {
    num: "111",
    name: "DEFAULT",
    img: "images/pkmn-img/111.png",
    shiny: "images/pkmn-img-shiny/111_s.png",
    altForm: "images/pkmn-img/111_e.png",
    altFormShiny: "images/pkmn-img-shiny/111_es.png",
    category: "Stray Dog Pokemon",
    ability: "Eternal Soul",
    height: "0,8m",
    weight: "35kg",
    evolution: [],
    cardColor: "#5b5464",
    pokemonTypes: [types.dark],
  },
  {
    num: "112",
    name: "DEFAULT",
    img: "images/pkmn-img/112.png",
    shiny: "images/pkmn-img-shiny/112_s.png",
    altForm: "images/pkmn-img/112_e.png",
    altFormShiny: "images/pkmn-img-shiny/112_es.png",
    category: "Stray Cat Pokemon",
    ability: "Eternal Soul",
    height: "0,5m",
    weight: "45kg",
    evolution: [],
    cardColor: "#fa7179",
    pokemonTypes: [types.psychic],
  },
  {
    num: "113",
    name: "GRASSIBEX",
    img: "images/pkmn-img/113.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Abundance Pokemon",
    ability: "Evergreen",
    height: "3m",
    weight: "200kg",
    evolution: [],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.water],
  },
  {
    num: "114",
    name: "PHANTERRION",
    img: "images/pkmn-img/114.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Drought Pokemon",
    ability: "Desolation",
    height: "3,3m",
    weight: "275kg",
    evolution: [],
    cardColor: "#ff9d55",
    pokemonTypes: [types.fire, types.ground],
  },
  {
    num: "115",
    name: "TURAIGUA",
    img: "images/pkmn-img/115.png",
    shiny: "images/pkmn-img-shiny/115_s.png",
    altForm: "",
    category: "Thunder Pokemon",
    ability: "Lighting Rod",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#f4d23c",
    pokemonTypes: [types.electric],
  },
  {
    num: "116",
    name: "TAENTÃ",
    img: "images/pkmn-img/116.png",
    shiny: "images/pkmn-img-shiny/116_s.png",
    altForm: "",
    category: "Flame Pokemon",
    ability: "Flash Fire",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#ff9d55",
    pokemonTypes: [types.fire],
  },
  {
    num: "117",
    name: "YOBIUNE",
    img: "images/pkmn-img/117.png",
    shiny: "images/pkmn-img-shiny/117_s.png",
    altForm: "",
    category: "River Pokemon",
    ability: "Storm Drain",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.water],
  },
  {
    num: "118",
    name: "DEFAULT",
    img: "images/pkmn-img/118.png",
    shiny: "images/pkmn-img-shiny/118_s.png",
    altForm: "",
    category: "Default",
    ability: "Planetary Body",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#5090d6",
    pokemonTypes: [types.water, types.psychic],
  },
  {
    num: "119",
    name: "DEFAULT",
    img: "images/pkmn-img/119.png",
    shiny: "images/pkmn-img-shiny/119_s.png",
    altForm: "",
    category: "Default",
    ability: "Planetary Body",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#63bc5a",
    pokemonTypes: [types.grass, types.psychic],
  },
  {
    num: "120",
    name: "DEFAULT",
    img: "images/pkmn-img/120.png",
    shiny: "images/pkmn-img-shiny/120_s.png",
    altForm: "",
    category: "Default",
    ability: "Planetary Body",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#d97845",
    pokemonTypes: [types.ground, types.psychic],
  },
  {
    num: "121",
    name: "DEFAULT",
    img: "images/pkmn-img/121.png",
    shiny: "images/pkmn-img-shiny/121_s.png",
    altForm: "",
    category: "Ancestor Pokemon",
    ability: "Speed Boost",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#ff9d55",
    pokemonTypes: [types.fire, types.psychic],
  },
  {
    num: "122",
    name: "GOGUAZUL",
    img: "images/pkmn-img/placeholder.png",
    shiny: "images/pkmn-img-shiny/placeholder.png",
    altForm: "",
    category: "Default",
    ability: "Default",
    height: "Default",
    weight: "Default",
    evolution: [],
    cardColor: "#8fa9de",
    pokemonTypes: [types.flying],
  },
  {
    num: "123",
    name: "WYSFLAMY",
    img: "images/pkmn-img/123.png",
    shiny: "images/pkmn-img-shiny/123_s.png",
    altForm: "",
    category: "Wisp Pokemon",
    ability: "Soul Fuel",
    height: "0,4m",
    weight: "0,1kg",
    evolution: [],
    cardColor: "#ff9d55",
    pokemonTypes: [types.fire, types.fairy],
  },
];
